### ISSUE TITLE
生成mesh时出现错误 生成mesh时出现错误 An error occurred while generating the mesh

### ISSUE THREAD

**Issue by ldj0o** [GAP-LAB-CUHK-SZ/gaustudio#4]
Thanks for your amazing work!

i use the following command to extract the mesh:
`gs-extract-mesh -m ./data/1750250955326095360_data/result -o ./output/1750250955326095360_data`

But the following errors will occur
```
Loading trained model at iteration 10000
./output/point_cloud/iteration_10000/point_cloud.ply
Traceback (most recent call last):
  File "/home/yxiong/anaconda3/envs/gaustudio/bin/gs-extract-mesh", line 33, in <module>
    sys.exit(load_entry_point('gaustudio', 'console_scripts', 'gs-extract-mesh')())
  File "/home/yxiong/gaustudio/gaustudio/gaustudio/scripts/extract_mesh.py", line 64, in main
    pcd.load(os.path.join(args.model,"point_cloud", "iteration_" + str(loaded_iter), "point_cloud.ply"))
  File "/home/yxiong/gaustudio/gaustudio/gaustudio/models/base.py", line 68, in load
    assert len(names) == self.config["attributes"][elem]
AssertionError
```
Is there any solution?

**Comment by hugoycj** [comment]
Apologies for the inconvenience. This error could be caused by a mismatch between the dimension numbers of specific properties. For instance, if the ply file has a spatial dimension (SH) of 2, which is different from the usual SH of 3, it could lead to this issue. 

Could you please share which method you used to train or generate the ply model?

**Comment by hugoycj** [comment]
Apologies for the inconvenience. This error could be caused by a mismatch between the dimension numbers of specific properties. For instance, if the splat file has a SH of 2, which is different from the usual SH of 3, it could lead to this issue. Could you please share the properties and dimensions of your ply model?

**Comment by ldj0o** [comment]
This is the property of my ply  model 

```
    system.init_dreamer="output/gs_init/kitchen" \
    system.refresh_size=8 \
    data.data_dir="data/mip360/kitchen" \
    data.resolution=8 \
    data.sparse_num=4 \
    data.prompt="a photo of a xxy5syt00" \
    data.refresh_size=8 \
    system.sh_degree=2 \
```
