### ISSUE TITLE
gs-extract-mesh

### ISSUE THREAD

**Issue by WS517** [GAP-LAB-CUHK-SZ/gaustudio#89]
Thanks for your great work, I tried to extract the results generated by octree-gs using gaustudio and got the following error:
![图片2](https://github.com/user-attachments/assets/d237a4cd-8427-424f-a84b-9694d1102549)

Loading trained model at iteration 40000
Loaded 485775 points from /home/wyj517/517/ws/gaustudio/data/jianzhuwu/point_cloud/iteration_40000/point_cloud.ply
Loading camera data from /home/wyj517/517/ws/gaustudio/data/cameras.json
  0%|                                                                                                                                                                                            | 0/80 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/wyj517/miniconda3/envs/gaustudio/bin/gs-extract-mesh", line 33, in <module>
    sys.exit(load_entry_point('gaustudio', 'console_scripts', 'gs-extract-mesh')())
  File "/home/wyj517/517/ws/gaustudio/gaustudio/scripts/extract_mesh.py", line 99, in main
    render_pkg = renderer.render(camera, pcd)
  File "/home/wyj517/517/ws/gaustudio/gaustudio/renderers/base.py", line 11, in render
    xyz, shs, colors_precomp, opacity, scales, rotations, cov3D_precomp = self.get_gaussians_properties(viewpoint_camera, gaussian_model)
  File "/home/wyj517/517/ws/gaustudio/gaustudio/renderers/vanilla_renderer.py", line 51, in get_gaussians_properties
    shs = gaussian_model.get_features
  File "/home/wyj517/517/ws/gaustudio/gaustudio/models/vanilla_sg.py", line 104, in get_features
    features_dc = self._f_dc.reshape(len(self._f_dc), -1, 3)
RuntimeError: cannot reshape tensor of 0 elements into shape [0, -1, 3] because the unspecified dimension size -1 can be any value and is ambiguous
What is the problem and how should I fix the issue? Is it that gaustudio is not able to perform facet extraction on octree-gs generated results? Looking forward to your reply, thank you very much!

**Comment by naveenmcv** [comment]
hi i am also getting the same error, any solutions ?
